# Generated by Django 6.0.2 on 2026-02-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_number", models.CharField(max_length=20, unique=True)),
                ("draw_date", models.DateField()),
                ("red_balls", models.JSONField()),
                ("blue_ball", models.IntegerField()),
                ("prize_pool", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-draw_date"],
            },
        ),
        migrations.CreateModel(
            name="NumberStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ball_number", models.IntegerField()),
                ("ball_type", models.CharField(choices=[("red", "Red"), ("blue", "Blue")], max_length=10)),
                ("frequency", models.IntegerField(default=0)),
                ("omission_count", models.IntegerField(default=0)),
                ("is_hot", models.BooleanField(default=False)),
                ("statistics_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-statistics_date", "ball_type", "ball_number"],
            },
        ),
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("predicted_numbers", models.JSONField()),
                ("algorithms_used", models.JSONField()),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("actual_result", models.JSONField(blank=True, null=True)),
                ("is_accurate", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
