# Generated by Django 6.0.2 on 2026-02-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hexagram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True, verbose_name="Hexagram Name")),
                ("sequence", models.PositiveIntegerField(unique=True, verbose_name="Sequence")),
                ("original_text", models.TextField(verbose_name="Original Text")),
                ("translation", models.TextField(verbose_name="Translation")),
                ("xiang_chuan", models.TextField(verbose_name="Xiang Chuan")),
                ("tuan_chuan", models.TextField(verbose_name="Tuan Chuan")),
            ],
            options={
                "verbose_name": "Hexagram",
                "verbose_name_plural": "Hexagrams",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveSmallIntegerField(verbose_name="Position")),
                ("original_text", models.TextField(verbose_name="Original Text")),
                ("translation", models.TextField(verbose_name="Translation")),
                ("xiao_xiang", models.TextField(verbose_name="Xiao Xiang")),
                ("nature", models.PositiveSmallIntegerField(choices=[(0, "Yin"), (1, "Yang")], verbose_name="Nature")),
                (
                    "auspiciousness",
                    models.CharField(
                        choices=[
                            ("great_fortune", "Great Fortune"),
                            ("fortune", "Fortune"),
                            ("average", "Average"),
                            ("misfortune", "Misfortune"),
                            ("great_misfortune", "Great Misfortune"),
                        ],
                        max_length=20,
                        verbose_name="Auspiciousness",
                    ),
                ),
                (
                    "hexagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="api.hexagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Line",
                "verbose_name_plural": "Lines",
                "ordering": ["hexagram", "position"],
                "unique_together": {("hexagram", "position")},
            },
        ),
        migrations.CreateModel(
            name="Interpretation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("career", "Career"),
                            ("wealth", "Wealth"),
                            ("emotion", "Emotion"),
                            ("health", "Health"),
                            ("litigation", "Litigation"),
                            ("travel", "Travel"),
                            ("exam", "Exam"),
                        ],
                        max_length=20,
                        verbose_name="Topic",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("suggestions", models.JSONField(default=list, verbose_name="Suggestions")),
                (
                    "hexagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="interpretations", to="api.hexagram"
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretations",
                        to="api.line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interpretation",
                "verbose_name_plural": "Interpretations",
                "ordering": ["hexagram", "line", "topic"],
                "indexes": [
                    models.Index(fields=["hexagram", "topic"], name="api_interpr_hexagra_1507b8_idx"),
                    models.Index(fields=["line", "topic"], name="api_interpr_line_id_f0b346_idx"),
                ],
            },
        ),
    ]
